### ISSUE TITLE
Error during installing package.

### ISSUE THREAD

**Issue by fstizza** [dreixel/generic-deriving#66] opened 2019-12-02 13:43 UTC
Hello, I was trying to install this package and this error came to me.

src/Generics/Deriving/TH/Pre4_9.hs:177:20:
    parse error on input ‘->’
Failed to install generic-deriving-1.13.1
cabal: Error: some packages failed to install:
generic-deriving-1.13.1 failed during the building phase. The exception was:
ExitFailure 1

I will appreciate if you get the solution of this. Thank you!

**Comment by RyanGlScott** [comment] 2019-12-02 16:27
Hm, I haven't observed this error before (nor has CI). Can you describe how to reproduce this? For instance, if you used `cabal`, can you try rerunning the same command with the `-v3` flag so that it prints out the full build plan?

**Comment by FedericoStizza** [comment] 2019-12-02 19:45
Sorry, I did reboot on mi PC and it started working.

**Comment by FedericoStizza** [comment] 2019-12-02 19:51
It happened again, here is a part of the log. I tried to install it using
cabal install generic-deriving -v3

*** Deleting temp files:
Deleting: /tmp/ghc78f6_0/ghc_120.c /tmp/ghc78f6_0/ghc_119.s
/tmp/ghc78f6_0/ghc_118.c /tmp/ghc78f6_0/ghc_117.s /tmp/ghc78f6_0/ghc_116.s
Warning: deleting non-existent /tmp/ghc78f6_0/ghc_120.c
Warning: deleting non-existent /tmp/ghc78f6_0/ghc_118.c
Warning: deleting non-existent /tmp/ghc78f6_0/ghc_116.s
compile: input file /tmp/ghc78f6_0/ghc_20.hscpp
*** Checking old interface for Generics.Deriving.TH.Pre4_9:
[21 of 22] Compiling Generics.Deriving.TH.Pre4_9 (
src/Generics/Deriving/TH/Pre4_9.hs,
dist/build/Generics/Deriving/TH/Pre4_9.o )
*** Parser:

src/Generics/Deriving/TH/Pre4_9.hs:177:20:
    parse error on input ‘->’
Upsweep partially successful.
*** Deleting temp files:
Deleting: /tmp/ghc78f6_0/ghc_121.s /tmp/ghc78f6_0/ghc_20.hscpp
/tmp/ghc78f6_0/ghc_15.hscpp
Warning: deleting non-existent /tmp/ghc78f6_0/ghc_121.s
link(batch): upsweep (partially) failed OR
   Main.main not exported; not linking.
*** Deleting temp files:
Deleting: /tmp/ghc78f6_0/ghc_19.hscpp /tmp/ghc78f6_0/ghc_18.hscpp
/tmp/ghc78f6_0/ghc_17.hscpp /tmp/ghc78f6_0/ghc_16.hscpp
/tmp/ghc78f6_0/ghc_14.hscpp /tmp/ghc78f6_0/ghc_13.hscpp
/tmp/ghc78f6_0/ghc_12.hscpp /tmp/ghc78f6_0/ghc_11.hscpp
/tmp/ghc78f6_0/ghc_10.hscpp /tmp/ghc78f6_0/ghc_9.hscpp
/tmp/ghc78f6_0/ghc_8.hscpp /tmp/ghc78f6_0/ghc_7.hscpp
/tmp/ghc78f6_0/ghc_6.hscpp /tmp/ghc78f6_0/ghc_5.hscpp
/tmp/ghc78f6_0/ghc_4.hscpp /tmp/ghc78f6_0/ghc_3.hscpp
/tmp/ghc78f6_0/ghc_2.hscpp /tmp/ghc78f6_0/ghc_1.hscpp
*** Deleting temp dirs:
Deleting: /tmp/ghc78f6_0
/usr/bin/ghc returned ExitFailure 1
Failed to install generic-deriving-1.13.1
World file is already up to date.
cabal: Error: some packages failed to install:
generic-deriving-1.13.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by RyanGlScott** [comment] 2019-12-03 07:22
Is that the entirety of the build log? Usually there is more before that which says exactly what combination of dependencies and build flags are enabled, which is the information I'm looking for.

For some reason, you're building the module `Generics.Deriving.Pre4_9` with an invalid combination of `base` and `template-haskell`. Normally, this sort of thing should be ruled out by this logic in `generic-deriving.cabal`:

https://github.com/dreixel/generic-deriving/blob/21c844061e2de8ed2118ae80bb3aee7e6d5d89c8/generic-deriving.cabal#L77-L82

For some reason, that's not happening, which makes me suspect something strange is going on with your version bounds. This is why I'd like to see the full `-v3` build log, since it will let me figure out exactly which versions of things you're trying to use (and help better diagnose what is going wrong).

**Comment by RyanGlScott** [comment] 2023-07-26 11:07
Closing due to a lack of information and an inability to reproduce the issue.

**Closed by RyanGlScott** 2023-07-26 11:07 UTC
Labels: info needed
