### ISSUE TITLE
Should `GFoldable' (Rec1 f)` be constrained by `Foldable`

### ISSUE THREAD

**Issue by Icelandjack** [dreixel/generic-deriving#76] opened 2021-08-29 13:53 UTC
I tried making a `Foldable` instance of [`Generically1`](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5726) so that I could derive

```haskell
data Queue a = Queue [a] (Reverse [] a)
  deriving stock Generically1
  deriving Foldable via Generically1 Queue
```
and it seemed like 
```haskell
instance GFoldable f => GFoldable' (Rec1 f) where
  gfoldMap' f (Rec1 a) = gfoldMap f a
``` 
needed to be changed to `Foldable`
```haskell
instance Foldable f => GFoldable' (Rec1 f) where
  gfoldMap' f (Rec1 a) = foldMap f a
```

**Comment by RyanGlScott** [comment] 2021-08-29 15:06
This is by design, as the `GFoldable` class is meant to be a pedagogical example that is separate from the `Foldable` class in `base`. [The `README`](https://github.com/dreixel/generic-deriving/blob/c97f2d7c691db8d0c2ca0b5ad439518b74ada6d6/README.md) talks about this:

> It is worth emphasizing that these modules are primarly intended for educational purposes. Many of the classes in these modules resemble other commonly used classes—for example, `GShow` from `Generics.Deriving.Show` resembles `Show` from `base`—but in general, the classes that `generic-deriving` defines are not drop-in replacements. Moreover, the generic defaults that `generic-deriving` provide often make simplifying assumptions that may violate expectations of how these classes might work elsewhere. For example, the generic default for `GShow` does not behave exactly like `deriving Show` would.
>
> If you are seeking `GHC.Generics`-based defaults for type classes in `base`, consider using the [`generic-data`](http://hackage.haskell.org/package/generic-data) library.

As such, I'm going to close this as being outside the scope of `generic-deriving`.

**Closed by RyanGlScott** 2021-08-29 15:06 UTC
